# Generated by Django 3.2.12 on 2022-06-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0004_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Is_admin',
        ),
    ]
