# Generated by Django 3.2.12 on 2022-06-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_management', '0005_remove_staff_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Subjects',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastonline',
        ),
    ]
